development:
  adapter: postgresql
  encoding: unicode
  database: news_evaluate
  username: dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: news_evaluate_test
  username: dev
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: news_evaluate
  username: dev
  pool: 5
  timeout: 5000
